### ISSUE TITLE
2D NATTEN Typo?

### ISSUE THREAD

**Issue by zaptrem** [pytorch-labs/attention-gym#11]
https://github.com/pytorch-labs/attention-gym/blob/bf80fecf39edee616be620ed6204aec786403b9a/examples/flex_attn.ipynb

```py
W = 128
H = 128
WINDOW = 8
def get_x_y(idx):
    return idx // W, idx % W
def natten_mask(b, h, q_idx, kv_idx):
    q_x, q_y = get_x_y(q_idx)
    kv_x, kv_y = get_x_y(kv_idx)
    horizontal_mask = (q_x - kv_x).abs() <= WINDOW
    vertical_mask = (q_y - kv_y).abs() <= WINDOW
    return horizontal_mask & vertical_mask
```

H is unused, maybe it should be removed so people don't think `get_x_y` should actually be `idx // W, idx % H` or something?

Also, why does natten_mask take b and h as params then not use them? Also X2, how do we avoid recreating masks on every forward pass without specifying height and width ahead of time? My model changes height and width a lot throughout the layers and during inference so I'd like to just set/recreate them based on the input shape received. I don't want to mess up torch.compile by introducing a side effect, though.

**Comment by Chillee** [comment]
> H is unused, maybe it should be removed

I think that's correct in this case. To translate from the flattened 1-d position to your 2d position, you only need the length of the row and not necessarily the column. Perhaps it should be removed in this example, although we should also clarify that this isn't "real" natten as well haha.

> Also, why does natten_mask take b and h as params then not use them?

The function signature of `mask_mod` is that it always takes in 4 scalar tensors, `b`, `h`, q_idx`, and `kv_idx`. The function then returns whether `score[b, h, q_idx, kv_idx]` should be used in the mask or not. 

As for handling the changing height/width, it kinda depends on how rapidly it's changing. If it's changing too much, you'd want dynamic shape support, which I'm not sure we support yet.
