### ISSUE TITLE
It seems that `visualize_attention_scores` can only visualize either mask-mod-only or score-mod-only

### ISSUE THREAD

**Issue by XinDongol** [pytorch-labs/attention-gym#29]
https://github.com/pytorch-labs/attention-gym/blob/75867424a1d4391bff49527029d3612a09dd67e2/attn_gym/utils.py#L68

**Comment by drisspg** [comment]
Do you have an example that needs both? It should deff be possible to extend it to visualize both

**Comment by XinDongol** [comment]
For example, if we want to apply `Alibi positional embedding`/`soft-cap` within the `sliding window`, a `visualize_attention_scores` that supports both will be very useful.
