### ISSUE TITLE
Integration with Hugginface Transformers

### ISSUE THREAD

**Issue by buaacyw** [pytorch-labs/attention-gym#30]
Thanks for your great contributions!
My repo currently highly rely on the Hugginface Transformers [repo](https://github.com/huggingface/transformers).
But unfortunately it doesn't support prefix causal attention, so I am looking to replace its attention mechanism with the one implemented in this repository. 
I have understood how to use this repository from [here](https://pytorch.org/blog/flexattention/), but I'm not quite sure how to integrate it into Huggingface Transformers. 
Do you have any experience or guidance on this? Considering the popularity of the Transformers repository, integrating flexattention into it could significantly increase its impact.
Thanks!

**Comment by drisspg** [comment]
Spoke with some folks on the HF side and they have this open: https://github.com/huggingface/transformers/issues/32877

When this is completed will likely be a good reference on how to integrate into HF models
