### ISSUE TITLE
Question about OOm on large sequences

### ISSUE THREAD

**Issue by foreverpiano** [pytorch-labs/attention-gym#32]
shape of q, k, v 
torch.Size([2, 12, 93600, 128]) torch.Size([2, 12, 93600, 128]) torch.Size([2, 12, 93600, 128])
and give error

**Comment by foreverpiano** [comment]
@drisspg

**Comment by foreverpiano** [comment]
Another error: materialize [93600, 93600] mask causes OOM, which is not as memory-efficient as xformer.

**Comment by Leo-T-Zang** [comment]
In their blog post, they will address it soon. Not supported for now I think.
https://pytorch.org/blog/flexattention/#limitations-and-future-work

> shape of q, k, v torch.Size([2, 12, 93600, 128]) torch.Size([2, 12, 93600, 128]) torch.Size([2, 12, 93600, 128]) and give error

**Comment by Chillee** [comment]
> Another error: materialize [93600, 93600] mask causes OOM, which is not as memory-efficient as xformer.

I would recommend passing `_compile` to `create_block_mask`. You can check out https://pytorch.org/blog/flexattention/#q-how-can-we-compute-blockmask-quicker for more details

**Comment by joydddd** [comment]
> 93600

Is this fixed in PyTorch Nightly? We added support for non multiple of 128 q_len & kv_len.

**Comment by foreverpiano** [comment]
@joydddd  let me check with it. I have another question. Is the dim dimension must be divide by 128 (for triton limit)?

**Comment by joydddd** [comment]
No, dim dimension can be anything that's 2^N and >16. For example, 32, 64, 128 should work.

**Comment by foreverpiano** [comment]
Got it. 96 should not work. Is it about triton limit? @joydddd

**Comment by drisspg** [comment]
96 will be supported but until we land a few updates from upstream trtion we can not land:
https://github.com/pytorch/pytorch/pull/133495
