### ISSUE TITLE
torch.nn.attention folder seems to be missing on torch 2.5 

### ISSUE THREAD

**Issue by kchl5** [pytorch-labs/attention-gym#36]
I was trying to install flex_attention and followed the proposed installation path, also I have installed attention-gym:

I have tried both highly and on torch 2.50, see below:

torch                    2.5.0.dev20240910+cu121
torchaudio               2.5.0.dev20240910+cu121
torchmetrics             1.4.1
torchvision              0.20.0.dev20240910+cu121

Even with both of these approaches, I encounter the following errors:

    from torch.nn.attention.flex_attention import create_block_mask
ModuleNotFoundError: No module named 'torch.nn.attention.flex_attention'

**Comment by drisspg** [comment]
hmm that is strange, let me double check this

**Comment by drisspg** [comment]
<img width="570" alt="Screenshot 2024-09-11 at 9 47 32 AM" src="https://github.com/user-attachments/assets/082e7e4f-1667-4fc2-8867-3a8d3e6a3173">

I am unable to repro this ... hmm

**Comment by kchl5** [comment]
Thanks for looking into this. I have managed to reproduce your code by only installing torch 2.5 using the command below:
```
pip3 install torch==2.5.0 --index-url https://down
load.pytorch.org/whl/test/cu121
```
I finally managed to install it. For my last attempt, I also installed torchvision and torchaudio which might have changed the torch installation. Hence, I am closing the issue.
