### ISSUE TITLE
Returned lse elements are all 0s

### ISSUE THREAD

**Issue by 311dada** [pytorch-labs/attention-gym#37]
Thanks for the great work! However, I found the returned lse elements of FlexAttention are all zeros. Could you please offer any help on this?

**Comment by drisspg** [comment]
Do you have a repro?

**Comment by 311dada** [comment]
Sorry for my late reply! Here is a code snippet:

```
from torch.nn.attention.flex_attention import (
    flex_attention,
)
import torch, math

flex_attention = torch.compile(flex_attention)


B, H, kv_H, S, D = 2, 32, 32, 128, 64

Q = torch.randn(B, H, S, D, dtype=torch.bfloat16).cuda()
K = torch.randn(B, kv_H, S, D, dtype=torch.bfloat16).cuda()
V = torch.randn(B, kv_H, S, D, dtype=torch.bfloat16).cuda()


output, flex_lse = flex_attention(Q, K, V, enable_gqa=True, return_lse=True)

eager_lse = torch.logsumexp(Q @ K.transpose(-2, -1) / math.sqrt(D), dim=-1)

print(eager_lse[0, 0])
print(flex_lse[0, 0])
```

In my machine, running the above code I got the following result:

```
tensor([5.4688, 5.7188, 5.2500, 5.3125, 5.3750, 5.3750, 5.0625, 5.1875, 5.5625,
        5.3125, 5.4375, 5.2500, 5.2500, 5.4375, 5.3750, 5.5000, 5.4375, 5.3750,
        5.2812, 5.3750, 5.3125, 5.2500, 5.3438, 5.2812, 5.1250, 5.2188, 5.3750,
        5.2500, 5.2812, 5.3125, 5.4375, 5.3125, 5.3750, 5.0938, 5.2812, 5.2500,
        5.2500, 5.1250, 5.1875, 5.1875, 5.1250, 5.4062, 5.6250, 5.2500, 5.0625,
        5.4062, 5.3750, 5.2500, 5.3750, 5.5000, 5.2188, 5.7500, 5.3750, 5.7500,
        5.2500, 5.1562, 5.4688, 5.3750, 5.5625, 5.2500, 5.1875, 5.0625, 5.0625,
        5.1250, 5.3750, 5.1875, 5.1562, 5.4688, 5.4375, 5.4375, 5.3438, 5.2500,
        5.3125, 5.1562, 5.3125, 5.3438, 5.2500, 5.2500, 5.4375, 5.5000, 5.3125,
        5.3750, 5.5625, 5.5625, 5.5000, 5.3750, 5.0938, 5.3125, 5.2812, 5.7188,
        5.3750, 5.1875, 5.3438, 5.5000, 5.1250, 5.3125, 5.3125, 5.5000, 5.4375,
        5.3125, 5.1562, 5.5000, 5.1875, 5.4062, 5.3750, 5.3438, 5.3750, 5.2500,
        5.6250, 5.2500, 5.4375, 5.4375, 5.4375, 5.3125, 5.3125, 5.3438, 5.2500,
        5.4375, 5.3750, 5.2500, 5.2500, 5.2500, 5.5000, 5.2500, 5.4375, 5.3125,
        5.4375, 5.4062], device='cuda:0', dtype=torch.bfloat16)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0')
```

**Comment by 311dada** [comment]
> Sorry for my late reply! Here is a code snippet:
> 
> ```
> from torch.nn.attention.flex_attention import (
>     flex_attention,
> )
> import torch, math
> 
> flex_attention = torch.compile(flex_attention)
> 
> 
> B, H, kv_H, S, D = 2, 32, 32, 128, 64
> 
> Q = torch.randn(B, H, S, D, dtype=torch.bfloat16).cuda()
> K = torch.randn(B, kv_H, S, D, dtype=torch.bfloat16).cuda()
> V = torch.randn(B, kv_H, S, D, dtype=torch.bfloat16).cuda()
> 
> 
> output, flex_lse = flex_attention(Q, K, V, enable_gqa=True, return_lse=True)
> 
> eager_lse = torch.logsumexp(Q @ K.transpose(-2, -1) / math.sqrt(D), dim=-1)
> 
> print(eager_lse[0, 0])
> print(flex_lse[0, 0])
> ```
> 
> In my machine, running the above code I got the following result:
> 
> ```
> tensor([5.4688, 5.7188, 5.2500, 5.3125, 5.3750, 5.3750, 5.0625, 5.1875, 5.5625,
>         5.3125, 5.4375, 5.2500, 5.2500, 5.4375, 5.3750, 5.5000, 5.4375, 5.3750,
>         5.2812, 5.3750, 5.3125, 5.2500, 5.3438, 5.2812, 5.1250, 5.2188, 5.3750,
>         5.2500, 5.2812, 5.3125, 5.4375, 5.3125, 5.3750, 5.0938, 5.2812, 5.2500,
>         5.2500, 5.1250, 5.1875, 5.1875, 5.1250, 5.4062, 5.6250, 5.2500, 5.0625,
>         5.4062, 5.3750, 5.2500, 5.3750, 5.5000, 5.2188, 5.7500, 5.3750, 5.7500,
>         5.2500, 5.1562, 5.4688, 5.3750, 5.5625, 5.2500, 5.1875, 5.0625, 5.0625,
>         5.1250, 5.3750, 5.1875, 5.1562, 5.4688, 5.4375, 5.4375, 5.3438, 5.2500,
>         5.3125, 5.1562, 5.3125, 5.3438, 5.2500, 5.2500, 5.4375, 5.5000, 5.3125,
>         5.3750, 5.5625, 5.5625, 5.5000, 5.3750, 5.0938, 5.3125, 5.2812, 5.7188,
>         5.3750, 5.1875, 5.3438, 5.5000, 5.1250, 5.3125, 5.3125, 5.5000, 5.4375,
>         5.3125, 5.1562, 5.5000, 5.1875, 5.4062, 5.3750, 5.3438, 5.3750, 5.2500,
>         5.6250, 5.2500, 5.4375, 5.4375, 5.4375, 5.3125, 5.3125, 5.3438, 5.2500,
>         5.4375, 5.3750, 5.2500, 5.2500, 5.2500, 5.5000, 5.2500, 5.4375, 5.3125,
>         5.4375, 5.4062], device='cuda:0', dtype=torch.bfloat16)
> tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
>         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
>         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
>         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
>         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
>         0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0')
> ```
> 
> May I ask if there is something wrong with how I am using it?

The problem is solved by updating torch to the latest version! I close the issue now.
