### ISSUE TITLE
Performance dependent on GPU type?

### ISSUE THREAD

**Issue by alex-hh** [pytorch-labs/attention-gym#49]
Hi, is flex attention performance dependent on GPU type?

Do you have any (anecdotal or quantitative) estimates of performance improvements for different GPU types?

(Related to #21 )

**Comment by joydddd** [comment]
Hi ALex, when you say GPU types, do you mean NV vs AMD, or V100 vs H100? 

Flex Attention has hand written heuristics for A100 & H100, therefore it should perform best on these GPUs out of the box. For other models, you might want to turn on `max_autotune` to generate the optimal performance. We're working on generating some performance comparisons on different GPUs, and will update once we get them.

**Comment by alex-hh** [comment]
Hi - thanks for the reply!

I meant more V100 vs H100 etc.

thanks for the tips - and look forward to performance comparisons!
