### ISSUE TITLE
torch compile issues with create_block_mask

### ISSUE THREAD

**Issue by tsengalb99** [pytorch-labs/attention-gym#94]
I have a function that returns a very simple block mask:

```
    def get_mask(self, b, h, n, device):
        def _mask(b, h, q_idx, kv_idx):
            q_tok = q_idx // (8 + 1)
            kv_tok = kv_idx // (8 + 1)
            return q_tok >= kv_tok
        return flex_attention.create_block_mask(
            _mask, None, None, n * (8 + 1), n * (8 + 1), device)
```

Calling this function fails at the torch compile step with the error `torch._dynamo.exc.Unsupported: call_function UserDefinedObjectVariable(BlockMask) [TensorVariable(), TensorVariable(), TensorVariable(), TensorVariable(), TensorVariable()] {}`. How do I fix this? I'm using torch nightly (2.6.0.dev20241222+cu124).

**Comment by drisspg** [comment]
Can you create a reference I.e.
```
create_block_mask_compiled = torch.compile(flex_attention.create_block_mask)

    def get_mask(self, b, h, n, device):
        def _mask(b, h, q_idx, kv_idx):
            q_tok = q_idx // (8 + 1)
            kv_tok = kv_idx // (8 + 1)
            return q_tok >= kv_tok
        return create_block_mask_compiled(_mask, None, None, n * (8 + 1), n * (8 + 1), device)
```

**Comment by tsengalb99** [comment]
I still get the same error. What version of torch are you using?

**Comment by drisspg** [comment]
I am using the nightly, what version are you using?

**Comment by tsengalb99** [comment]
`2.6.0.dev20241222+cu124`. So it turns out I was passing in the mask in wrong in the actual flex attention call and that was where torch compile was failing. I fixed it and it seems to work fine now.
